import { ICondition } from "./ICondition";

export interface ICurrent {
    condition: ICondition,
    temp_c: number,
    temp_f: number,
    wind_mph: number,
    wind_kph: number,
    wind_degree: number,
    pressure_mb: number,
    pressure_in: number,
    humidity: number,
    cloud: number,
    vis_km: number,
    vis_miles: number,
    uv: number,
    gust_mph: number,
    gust_kph: number,
    dewpoint_c?: number,
    dewpoint_f?: number,
    will_it_rain?: number,
    chance_of_rain?: number,
    will_it_snow?: number,
    chance_of_snow?: number,
}